baseURL = "https://raol.io/"
languageCode = "en-us"
title = "Raol.io"
publishDir = "docs"
theme="ghostwriter"

[params]
intro = true
headline = "Thoughts on software engineering."
twitter = "https://twitter.com/raoldev"
github = "https://github.com/raol"
author = "Oleg Rakitskiy"
